"""Language name added to Language model

Revision ID: 155c3ebe2a0a
Revises: ef6554b12cd8
Create Date: 2017-01-01 17:05:03.349240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155c3ebe2a0a'
down_revision = 'ef6554b12cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'name')
    # ### end Alembic commands ###
