"""Language code should be unique

Revision ID: 84994003a7ff
Revises: 155c3ebe2a0a
Create Date: 2017-01-01 18:07:26.020276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84994003a7ff'
down_revision = '155c3ebe2a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_languages_code', table_name='languages')
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.create_index('ix_languages_code', 'languages', ['code'], unique=False)
    # ### end Alembic commands ###
