"""Language name column removed

Revision ID: 877746360cc0
Revises: 84994003a7ff
Create Date: 2017-01-06 18:23:25.775072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877746360cc0'
down_revision = '84994003a7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
