"""empty message

Revision ID: ef6554b12cd8
Revises: 
Create Date: 2016-12-31 18:14:47.504511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6554b12cd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiments', sa.Column('score', sa.Float(), nullable=True))
    op.drop_column('sentiments', 'is_negative')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiments', sa.Column('is_negative', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sentiments', 'score')
    # ### end Alembic commands ###
